### ISSUE TITLE
Registration duplicated in the database

### ISSUE THREAD

**Issue by fisal77** [SALLEMAPP/sallem-app#1]
In Registration activity if the user name (Email) already exists, app must provide forgotten password resend option or redirect the user to the login activity page and not repeat the registration in the database.

The expected result: as TC-2.

![image](https://cloud.githubusercontent.com/assets/23268583/25065777/071f5c5e-221e-11e7-9bb5-f45dbbfbc9c7.png)

@bamusasoft @ahmedhussam2002 @Amoudi86

**Comment by bamusasoft** [comment]
Fixed. Try it now . It will show invalid message when you enter a already used email

**Comment by fisal77** [comment]
Thank You !
