### ISSUE TITLE
No message for Friendship Send Request

### ISSUE THREAD

**Issue by fisal77** [SALLEMAPP/sallem-app#6]
After click Send Request blue button no any message appear that inform user his request has been sent.

The expected result: as TC-7

![image](https://cloud.githubusercontent.com/assets/23268583/25066158/4d8b2aca-2227-11e7-90e5-7c112c20390e.png)

@bamusasoft @ahmedhussam2002 @Amoudi86

**Comment by bamusasoft** [comment]
fixed. Try it now. Notification will be sent when friendship request created

**Comment by fisal77** [comment]
Thank you ! the issue has been solved !
