### ISSUE TITLE
When click on Settings menu, app unfortunately stopped

### ISSUE THREAD

**Issue by fisal77** [SALLEMAPP/sallem-app#7]
When click on Settings menu, app unfortunately stopped.
The expected result: as TC-9

Debug:

FATAL EXCEPTION: main Process: com.seniorproject.sallemapp, PID: 18794
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Switch.setChecked(boolean)' on a null object reference 
at com.seniorproject.sallemapp.Activities.SettingsFragment.initSettings(SettingsFragment.java:101) 
at com.seniorproject.sallemapp.Activities.SettingsFragment.onCreateView(SettingsFragment.java:80)

![image](https://cloud.githubusercontent.com/assets/23268583/25071001/e9ef94ae-22b4-11e7-828a-106e1dd4811b.png)

@bamusasoft 
@ahmedhussam2002 @SALLEMAPP @Amoudi86

**Comment by bamusasoft** [comment]
Fixed. Try it again please
